Feat upgrade polaris
polarismesh/dubbo-java-polaris pull request #23
Opened 2023-05-13 01:20 UTC by chuntaojun

- update router and limit plugin import java package
- support new circuitbreaker ability

2023-05-15 06:54 UTC, pengkai242 commented
OK

2023-05-15 07:01 UTC, SkyeBeFreeman requested changes

2023-05-15 07:01 UTC, SkyeBeFreeman commented on pom.xml
> +        <polaris.version>1.12.4</polaris.version>
使用1.12.5版本

2023-05-15 07:03 UTC, SkyeBeFreeman commented on pom.xml
> +        <revision>0.1.4-SNAPSHOT</revision>
加了熔断的话，是不是可以搞成0.2.0-SNAPSHOT？

2023-05-15 07:03 UTC, SkyeBeFreeman commented on dubbox/dubbox-plugins/dubbox-router-polaris/src/main/java/com/tencent/polaris/dubbox/router/InstanceInvoker.java
> -        String circuitBreakerStr = url.getParameter(Consts.INSTANCE_KEY_CIRCUIT_BREAKER);
这里删除后，实例级熔断在哪里实现呢？

2023-05-16 02:11 UTC, SkyeBeFreeman approved these changes
LGTM.

2023-05-16 02:11 UTC, merged